---
- name: change cafe-example to include env demo variable
  copy:
    src: "{{ role_path }}/files/cafe.yaml"
    dest: $HOME/kubernetes-ingress/examples/complete-example/cafe.yaml

- name: add env demo service to cafe ingress
  copy:
    src: "{{ role_path }}/files/cafe-example.yaml"
    dest: $HOME/kubernetes-ingress/examples/complete-example/cafe-ingress.yaml

- name: deploy cafe example to kubernetes 
  shell: "/usr/local/bin/kubectl --kubeconfig /etc/kubernetes/admin.conf create -f $HOME/kubernetes-ingress/examples/complete-example/{{ item }}"
  with_items:
    - cafe.yaml
    - cafe-secret.yaml
    - cafe-ingress.yaml
