---
- name: docker login
  command: "docker login -u {{ dockerhub_user }} -p {{ dockerhub_password }}"

- name: install git and clone kubernetes-ingress repo on master
  include: nginx-git.yml
  when: inventory_hostname in groups['kube-master']

- name: install nginx-plus private repo
  include: nginxrepo.yml
  when: inventory_hostname in groups['kube-master'] and {{ nginx_build }}

- name: pull image for nginx-plus
  command: "docker pull {{ dockerhub_user }}/{{ dockerhub_repo }}:{{ dockerhub_tag }}"

- name: install nginx-plus on master
  include: ingress.yml
  when: inventory_hostname in groups['kube-master']

- name: install nginx-plus on master
  include: cafe-example.yml
  when: inventory_hostname in groups['kube-master']