---
- name: docker login
  docker_login:
    username: "{{ dockerhub_user }}"
    password: "{{ dockerhub_password }}"

- name: install nginx-plus private repo
  include: nginxrepo.yml
  when: inventory_hostname in groups['masters']

- name: pull image for nginx-plus
  docker_image:
    name: "{{ dockerhub_user }}/{{ dockerhub_repo }}"
    tag: "{{ dockerhub_tag }}"

- name: install nginx-plus on master
  include: ingress.yml
  when: inventory_hostname in groups['masters']

- name: install nginx-plus on master
  include: cafe-example.yml
  when: inventory_hostname in groups['masters']