---
- name: clone multus git repo
  git:
    repo: https://github.com/intel/multus-cni.git
    dest: $HOME/multus-cni

- name: apply multus flannel daemonset
  shell: cat $HOME/multus-cni/images/{multus-daemonset.yml,flannel-daemonset.yml} | kubectl apply -f -

- name: apply multus flannel crio daemonset
  shell: cat $HOME/multus-cni/images/{multus-crio-daemonset.yml,flannel-daemonset.yml} | kubectl apply -f -

- name: make multus binary
  make:
    chdir: $HOME/multus-cni

- name: copy the binary to /opt/cni/bin
  copy:
    src: $HOME/multus-cni/bin/multus
    dest: /opt/cni/bin/multus
    remote_src: yes
