---
- name: update all packages
  yum:
    name: '*'
    state: latest

- name: enable EPEL repositories
  yum:
    name: epel-release
    state: present

- name: install docker, git and some tools
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - docker
    - go

- name: enable and start docker
  systemd:
    name: docker
    state: started
    enabled: yes
