---
- name: check go version
  command: go version
  register: result
  changed_when: no
  ignore_errors: true

- set_fact:
    go_path: "{{ lookup('env', 'GOPATH') | default(ansible_env.HOME+'/go', true) }}"
  when: not result|failed

- name: install crictl
  shell: go get -u github.com/kubernetes-incubator/cri-tools/cmd/crictl
  environment:
    GOPATH: "{{ go_path }}"
  register: crictl
  when: not result|failed

- debug: var=crictl
