---
- name: copy repo for kubernetes
  template:
    src: kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo

- name: install kube packages
  yum:
    name:
      - kubelet
      - kubeadmin
      - kubectl
    state: present

- name: enable and start kubelet
  systemd:
    name: kubelet
    state: started
    enabled: yes
