---
# tasks file for nginx-kube-demo
- name: Disable swap
  include: common/swapoff.yml
  tags: configure
  when: disable_swap

- name: Change selinux policy
  include: common/selinux.yml
  tags: configure

- name: Disable ivp6
  include: common/ipv6off.yml
  tags: configure
  when: disable_ipv6

- name: Disable firewalld
  include: common/firewalldoff.yml
  tags: configure
  when: disable_firewalld

- name: Enable firewalld
  include: common/firewalldon.yml
  tags: configure
  when: not disable_firewalld

- name: Modify docker bridge settings
  include: common/modifybridge.yml
  tags: configure
  when: modify_bridge

- name: Install Docker
  include: common/docker.yml
  tags: install

- name: Install crictl
  include: common/gocrictl.yml
  tags: install

- name: install common kubernetes components
  include: common/kubernetes.yml
  tags: install

# Install the kube master components
- name: Install kube master
  include: master/install.yml
  tags: install
  hosts: masters

# Install the kube node components
- name: Install kube node
  include: node/install.yml
  tags: install
  hosts: nodes
